# Generated by Django 5.2.4 on 2026-03-03 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'Hero / Banner principal'), ('text', 'Texto con imagen'), ('stats', 'Estadísticas / Cifras'), ('gallery', 'Galería de imágenes'), ('cta', 'Llamado a la acción')], default='text', max_length=20, verbose_name='Tipo de sección')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Subtítulo')),
                ('body', models.TextField(blank=True, help_text='Contenido enriquecido de la sección (acepta HTML).', verbose_name='Contenido (HTML)')),
                ('image', models.ImageField(blank=True, help_text='Imagen principal de la sección.', null=True, upload_to='about/sections/', verbose_name='Imagen')),
                ('background_color', models.CharField(blank=True, help_text='Ej: #e3f2e5, transparent, primary. Dejarlo vacío usa el tema.', max_length=30, verbose_name='Color de fondo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'sección',
                'verbose_name_plural': 'secciones',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/gallery/', verbose_name='Imagen')),
                ('alt', models.CharField(blank=True, max_length=120, verbose_name='Texto alternativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('section', models.ForeignKey(limit_choices_to={'section_type': 'gallery'}, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='about.aboutsection')),
            ],
            options={
                'verbose_name': 'imagen de galería',
                'verbose_name_plural': 'imágenes de galería',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80, verbose_name='Etiqueta')),
                ('value', models.CharField(help_text='Ej: 150+, 18, 5.300', max_length=40, verbose_name='Valor')),
                ('icon', models.CharField(blank=True, help_text='Nombre del icono de lucide-react, ej: tractor, users, map-pin', max_length=60, verbose_name='Icono (nombre Lucide)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('section', models.ForeignKey(limit_choices_to={'section_type': 'stats'}, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='about.aboutsection')),
            ],
            options={
                'verbose_name': 'estadística',
                'verbose_name_plural': 'estadísticas',
                'ordering': ['order', 'id'],
            },
        ),
    ]
