# Generated by Django 5.2.4 on 2025-07-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('cover_image', models.ImageField(upload_to='blog/covers/')),
                ('excerpt', models.CharField(blank=True, max_length=250)),
                ('content', models.TextField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
