# Generated by Django 5.2.4 on 2026-02-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSidebarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Texto Alt para la imagen', max_length=100)),
                ('image', models.ImageField(help_text='Imagen para el carrusel lateral', upload_to='blog/sidebar/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imagen Lateral Blog',
                'verbose_name_plural': 'Imágenes Lateral Blog',
                'ordering': ['-created_at'],
            },
        ),
    ]
