# Generated by Django 5.2.4 on 2025-07-06 17:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created_at'], 'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='city',
        ),
        migrations.RemoveField(
            model_name='client',
            name='country',
        ),
        migrations.AddField(
            model_name='client',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='clients/covers/'),
        ),
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='client',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='testimonial',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='ClientImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clients/gallery/')),
                ('alt', models.CharField(blank=True, max_length=120)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='clients.client')),
            ],
            options={
                'verbose_name': 'imagen de cliente',
                'verbose_name_plural': 'imagenes de clientes',
            },
        ),
    ]
