# Generated by Django 5.2.4 on 2026-03-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_latitude_alter_client_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created_at'], 'verbose_name': 'proyecto', 'verbose_name_plural': 'proyectos'},
        ),
        migrations.AlterModelOptions(
            name='clientimage',
            options={'verbose_name': 'imagen de proyecto', 'verbose_name_plural': 'imágenes de proyectos'},
        ),
        migrations.AddField(
            model_name='client',
            name='content',
            field=models.TextField(blank=True, help_text='Contenido enriquecido del proyecto (acepta HTML).', verbose_name='Contenido (HTML)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='client',
            name='testimonial',
            field=models.TextField(blank=True, verbose_name='Resumen corto'),
        ),
    ]
