# Generated by Django 5.2.4 on 2026-03-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_options_alter_clientimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, help_text='Imagen principal del banner.', null=True, upload_to='projects/banners/')),
                ('video_url', models.URLField(blank=True, help_text='URL de YouTube, TikTok u otra plataforma de video.', null=True, verbose_name='URL de video')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'banner de proyecto',
                'verbose_name_plural': 'banners de proyectos',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL de YouTube, TikTok u otra plataforma de video.', null=True, verbose_name='URL de video'),
        ),
    ]
