# Generated by Django 5.2.4 on 2026-02-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text='Especificaciones técnicas (clave-valor)'),
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL de YouTube, Vimeo o TikTok', null=True),
        ),
    ]
