# Generated by Django 5.2.4 on 2026-02-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_specifications_product_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(upload_to='products/carousel/')),
                ('link', models.URLField(blank=True, help_text='Enlace opcional al hacer clic', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'imagen carrusel productos',
                'verbose_name_plural': 'imágenes carrusel productos',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='hide_price',
            field=models.BooleanField(default=False, verbose_name='Ocultar precio'),
        ),
    ]
